version: '3'
services:
  ipfs-node:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_local
    ports:
      - "5001:5001"   # API IPFS
      - "8080:8080"   # Gateway
      - "4001:4001"   # Swarm
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs

volumes:
  ipfs_staging:
  ipfs_data:
